Added Label mixin for reuse across components
wmde/wikit pull request #214
Opened 2020-10-13 11:45 UTC by guergana

2020-10-13 13:00 UTC, jakobw requested changes
Am aware the whole stylelint sass part isn't done yet. Just leaving these comments here for early feedback!

2020-10-13 14:28 UTC, guergana commented on vue-components/src/styles/mixins/Label.scss
> +    color: $wikit-TextInput-input-color;
Ok. Now I understand, yes, it makes sense!

2020-10-13 15:11 UTC, guergana commented on package.json
> +    "stylelint-config-sass-guidelines": "^7.1.0"
updated

2020-10-13 17:15 UTC, itamargiv commented on vue-components/src/styles/mixins/Label.scss
> +    color: $wikit-TextInput-input-color;
sonds like a good idea to me, what does @SaiSan-WMDE think?

2020-10-14 05:30 UTC, Ladsgroup commented
A general note: Can the stylelinting be extracted to another PR? I feel they are separated stuff.

2020-10-14 08:56 UTC, jakobw reviewed
Looks good. Found one tiny code style thing to complain about, but otherwise good to go!

I agree with Amir that it's a bit hard to review because the lint changes affect the same file where the Label mixin is extracted, but looking at the commits individually helps.

2020-10-14 09:10 UTC, SaiSan-WMDE commented on vue-components/src/styles/mixins/Label.scss
> +    color: $wikit-TextInput-input-color;
Sorry for the late response! Agree to creating a new componen-level token file for the label mixin. Sounds like the best way to make it fully reusable and context-agnostic. I'd say that the later file name (tokens/properties/mixins/Label.json) makes more sense, though? It matches reality better. What do you all think?

Hate to be making @jakobw's life a nightmare lately 😅

2020-10-14 09:20 UTC, guergana commented on vue-components/src/styles/mixins/Label.scss
> +    color: $wikit-TextInput-input-color;
Hi, it's actually me working on this ticket @SaiSan-WMDE, I added the mixin in the mixin folder

2020-10-14 09:27 UTC, jakobw commented on vue-components/stylelint.config.js
> +		'selector-class-pattern': null,	},
```suggestion
		'selector-class-pattern': null,
	},
```

2020-10-14 09:37 UTC, guergana commented on vue-components/stylelint.config.js
> +		'selector-class-pattern': null,	},
It's fixed

2020-10-14 09:39 UTC, jakobw approved these changes
YAY :sparkles: :sparkles: :sparkles:

2020-10-14 09:45 UTC, SaiSan-WMDE commented on vue-components/src/styles/mixins/Label.scss
> +    color: $wikit-TextInput-input-color;
so that means that I'm also making your life a nightmare 🙊  Thanks, Guergana! 🙏

2020-10-14 09:46 UTC, guergana commented
> YAY sparkles sparkles sparkles

Crying with happiness.

2020-10-14 09:46 UTC, merged