Make OptionsMenu items controllable in Storybook
wmde/wikit pull request #304
Opened 2020-11-26 09:49 UTC by micgro42

2020-11-26 11:17 UTC, guergana commented
Looks good. Why is it a draft?

2020-11-26 15:55 UTC, micgro42 commented
> Looks good. Why is it a draft?

When it was created, it was unclear whether people would want it. Setting it ready for review now.

2020-11-26 16:55 UTC, itamargiv requested changes
Juhu, looks fantastic, I do have one qualm about the `menuItems` control. Also, I would ask @SaiSan-WMDE where the Options menu should go in terms of the storybook structure she envisioned.

2020-11-26 16:55 UTC, itamargiv commented on vue-components/stories/OptionsMenu.stories.ts
> +	menuItems: vegetableItems,
This control feels a bit cluncky, which makes me question how usable it actually is, maybe we should create a couple of controls for only one item from the list? (i.e. label, description, tag)

2020-11-26 17:44 UTC, SaiSan-WMDE commented
> Also, I would ask @SaiSan-WMDE where the Options menu should go in terms of the storybook structure she envisioned.

Well, first let me say that I'm actually against displaying internal subcomponents (such as the Input and the OptionsMenu) in our Storybook 😑  In my opinion, simply referring/pointing at them from the "finished" component's documentation should be enough. 

But I understand the engineers' position, so I would say that displaying the OptionsMenu in a separate section (as suggested by this PR) might make more sense than other options: displaying the component several times in its multiple parents' sections; or creating a separate subsection to collect internal components.

2020-12-14 10:09 UTC, micgro42 commented
Making this a draft again as it needs more conceptual work

2021-01-15 08:43 UTC, closed without merging