Fix pseudo-selector order
wmde/wikit pull request #367
Opened 2021-02-01 14:17 UTC by itamargiv

This PR aims to fix an issue with hover styles by correcting the pseudo selector order to reflect the overrides performed by the user. i.e. an element is:

1. First `:focus`ed (most general case)
2. Then `:hover`ed (specific case before activated, desktop only)
3. And only then potentially `:active`ated

In this case the selector cascade reflects that flow and thus does not require a higher specificity to perform overrides.

See: https://phabricator.wikimedia.org/T266557
Bug: T266557

2021-02-01 15:14 UTC, SaiSan-WMDE commented
Would it be possible to prevent the buttons' border from changing whenever a focused button is hovered? Only the button text color and the background color should be affected.

2021-02-02 10:01 UTC, jakobw requested changes
It bothers me a little bit to have `:focus:hover` mix and match styling from the two states without making this visible in the tokens. Was this considered? :thinking: 

Looks good in general and I like how the pseudo selectors are reordered! I left one small suggestion inline.

2021-02-02 10:35 UTC, SaiSan-WMDE commented on vue-components/src/components/Button.vue
> +				border-color: $wikit-Button-normal-neutral-hover-border-color;
Hey Jakob. So you mean that we should consider creating `$wikit-Button-xx-xx-focus-hovered` tokens? I thought about it, but concluded that creating new styles with the same values sounded a bit redundant :-/ Representing one pseudo selector level in the tokens seems enough. After all, the combination of pseudo selectors (in this or other cases) could be considered an implementation decision, right?

2021-02-02 11:09 UTC, jakobw commented
(I'm answering here because I don't think the comment thread is related to the code suggestion.)

Hey @SaiSan-WMDE!

> So you mean that we should consider creating $wikit-Button-xx-xx-focus-hovered tokens?

Something like that, yup!

> Representing one pseudo selector level in the tokens seems enough. After all, in general the combination of pseudo selectors (in this or other cases) could be considered an implementation decision, right?

I would agree if there was some cascading order that would lead to the desired behavior. Overriding some, but not all of the `:focus` properties on `:hover` means that there is no way we could arrive at the expected styling for the combination of the two based on the existing tokens.

It seems that this was considered though, so I'm ok with the decision! The change request was only for the code suggestion and not about the tokens.

2021-02-08 10:20 UTC, SaiSan-WMDE commented
> (I'm answering here because I don't think the comment thread is related to the code suggestion.)

Sorry about the wrongly nested response.

> I would agree if there was some cascading order that would lead to the desired behavior. Overriding some, but not all of the `:focus` properties on `:hover` means that there is no way we could arrive at the expected styling for the combination of the two based on the existing tokens.

I see the point and I agree in this instance, but I'd tentatively move forward expressing only single states styles in the tokens to avoid introducing redundancy.

Thanks so much for your feedback, Jakob 💯

2021-02-08 10:53 UTC, jakobw submitted a review, later dismissed
🚀

2021-02-08 11:55 UTC, SaiSan-WMDE approved these changes

2021-02-08 12:48 UTC, merged