Update eslint-related dependencies
wmde/wikit pull request #598
Opened 2022-06-15 14:28 UTC by micgro42

The `TextInput` component was adjusted to satisfy the error message:
```
94:3  error  Name "Input" is reserved in HTML  vue/no-reserved-component-names
```

2022-06-15 14:32 UTC, micgro42 commented
I don't get it. The error is here as well!?

Also, about that npm warning - where the heck is the `eslint-plugin-vue@6.2.2` coming from in the first place?

2022-06-15 14:40 UTC, micgro42 commented
> > The `TextInput` component was adjusted to satisfy the error message:
> 
> Doesn’t that also need to be changed in `LookupInput.vue`?

Mh, good point. But it didn't complain for LookupInput.vue :thinking:.  The only difference that I notice as first glance would be how the `Input` component is imported in each case?

2022-06-15 14:45 UTC, lucaswerkmeister commented
This is very strange, everything seems to be green locally (so, the package/lock errors aren’t there, but also, eslint isn’t complaining about `LookupInput`). I’m confused…

2022-06-16 16:18 UTC, lucaswerkmeister requested changes
LGTM apart from some leftover debug output (I assume); also works for me in Fresh

2022-06-16 16:18 UTC, lucaswerkmeister commented on .github/workflows/test-and-demo.yaml
> +      run: npm --version
```suggestion
```

2022-06-16 16:21 UTC, lucaswerkmeister approved these changes

2022-06-16 16:32 UTC, merged